# Generated by Django 2.2.12 on 2020-11-20 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Achievements', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Achiever',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=35)),
                ('Surnames', models.CharField(max_length=35)),
                ('BirthDay', models.DateField()),
                ('Description', models.CharField(max_length=200)),
                ('EMail', models.CharField(max_length=140)),
                ('Profile_Pictures', models.ImageField(upload_to='ProfilePictures')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_Achiever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Achiever', to='Achievers.Achiever')),
                ('FK_Follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Follower', to='Achievers.Achiever')),
                ('FK_Following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Following', to='Achievers.Achiever')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=300)),
                ('Unlocked', models.CharField(max_length=300)),
                ('FK_Achiever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Achievers.Achiever')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments', models.CharField(max_length=300)),
                ('FK_Achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Achievers.Achievement')),
                ('FK_Achiever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Achievers.Achiever')),
            ],
        ),
        migrations.AddField(
            model_name='achiever',
            name='FK_Following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Achievers.Relation'),
        ),
        migrations.AddField(
            model_name='achiever',
            name='FK_Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Achievers.Level'),
        ),
        migrations.AddField(
            model_name='achiever',
            name='Vinculation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='FK_Achiever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Achievers.Achiever'),
        ),
    ]
