# Generated by Django 2.2.12 on 2020-08-21 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=120)),
                ('dni', models.CharField(default='', max_length=8)),
                ('telefono', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechahora', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Cerrado'), ('E', 'En curso')], default='P', max_length=8)),
                ('descripcion', models.CharField(default='', max_length=250)),
                ('cliente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Cliente')),
            ],
            options={
                'ordering': ('-fechahora',),
            },
        ),
    ]
